#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
export LOCAL_ADMIN_SCRIPTS=/usr/facebook/ops/rc
FB_NO_ALIASES=true
source $LOCAL_ADMIN_SCRIPTS/master.zshrc

source ~/scm-prompt
# source $LOCAL_ADMIN_SCRIPTS/scm-prompt

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

alias ls='ls --color=auto -F'
alias -g fwdproxy='http_proxy=fwdproxy:8080 https_proxy=fwdproxy:8080'
alias -g N='2>&1 > /dev/null'
alias -g GC='sort | uniq -c | sort -n'
export LESS='-r'
export LESSOPEN='| ~/bin/lessfilter.sh %s'
export EDITOR=vim
export VISUAL=vim

for comp in arcanist argcomplete buck entschema flow smcc ; do
    source $LOCAL_ADMIN_SCRIPTS/bash-completion/$comp
done

source ~/.drox/shellfuncs.sh

function showcolors() {
    for code in {000..255}; do
        print -P -- "$code: %F{$code}Test%f";
    done
}

setopt interactivecomments

bindkey "^R" history-incremental-search-backward
bindkey "^P" up-line-or-history
bindkey "^N" down-line-or-history
bindkey "^A" beginning-of-line
bindkey "^E" end-of-line
