#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


source ~/.drox/shellfuncs.sh
source ~/.zsh.facebook
source ~/.zsh.custom

setopt interactivecomments
unsetopt correct_all
unsetopt correct


bindkey "^R" history-incremental-search-backward
bindkey "^P" up-line-or-history
bindkey "^N" down-line-or-history
bindkey "^A" beginning-of-line
bindkey "^E" end-of-line

bindkey '\e.' insert-last-word

export I_LUV_TMUX=1

export HISTORY_IGNORE="(ls|cd|pwd|exit|cd ..|hs)"

# put ~/bin at the front of the path
export PATH="/home/$USER/bin:$(echo $PATH | tr : '\n' | grep -v "/home/$USER/bin" | paste -sd:):/home/joxley/virtualenvs/pydev/bin"

export FZF_ALT_C_COMMAND='fasd -ld'
export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_DEFAULT_OPTS='--exact'
export FZF_TMUX=1
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
